# This file was generated by GoReleaser. DO NOT EDIT.
cask "gogo" do
  depends_on macos: :monterey

  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "gogo"], chdir: "."
    end
  end

  version "3.2.0"

  on_macos do
    on_arm do
      sha256 "f9d1f2c15e355740bb2278dc0f627bed3ff09236639657a9bb0364d52eb088c8"
      url "https://github.com/daFish/gogo-meta/releases/download/v#{version}/gogo_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "6d4ac67b6bf3163be13a66e121f058465ed8b15ddc19f770d35d4a3002231486"
      url "https://github.com/daFish/gogo-meta/releases/download/v#{version}/gogo_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "2ee9989b6820c75077740410abc038584a911fe9fb5061dca78943b735f92f79"
      url "https://github.com/daFish/gogo-meta/releases/download/v#{version}/gogo_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "88c6e9c977e7ef3d13ea18631534c3baae974a8252f79a717ae43b41c5521279"
      url "https://github.com/daFish/gogo-meta/releases/download/v#{version}/gogo_#{version}_linux_amd64.tar.gz"
    end
  end

  name "gogo"
  desc "Run commands across multiple Git repositories at once"
  homepage "https://github.com/daFish/gogo-meta"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gogo"

  # No zap stanza required
end
