# This file was generated by GoReleaser. DO NOT EDIT.
cask "gogo" do
  depends_on macos: :monterey

  version "3.1.1"

  on_macos do
    on_arm do
      sha256 "767888561c4ca133ae2ae4705a3019a4c2d0ca74b36d67aa47da6e6f9f9c7437"
      url "https://github.com/daFish/gogo-meta/releases/download/v#{version}/gogo_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "6b1ff398557a94a0eabcb34c1caf41ed2dc2fe1e89bfb65d8a92cfb8a2bcc3b3"
      url "https://github.com/daFish/gogo-meta/releases/download/v#{version}/gogo_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "9c9866a7394d583b7f90ff6f1c66f477645e1550f13db682528d5c66431af056"
      url "https://github.com/daFish/gogo-meta/releases/download/v#{version}/gogo_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "99d983d66f517fd741cef07885d7155ad1f78bf2cc970ddeb47ce03432938d7b"
      url "https://github.com/daFish/gogo-meta/releases/download/v#{version}/gogo_#{version}_linux_amd64.tar.gz"
    end
  end

  name "gogo"
  desc "Run commands across multiple Git repositories at once"
  homepage "https://github.com/daFish/gogo-meta"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gogo"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gogo"] if OS.mac?
  end

  # No zap stanza required
end
