# This file was generated by GoReleaser. DO NOT EDIT.
cask "gogo" do
  depends_on macos: :monterey

  version "3.0.1"

  on_macos do
    on_arm do
      sha256 "f60547fdcb80d3af074123f54764f6a16197246dfeea526b9796019ddaf85967"
      url "https://github.com/daFish/gogo-meta/releases/download/v#{version}/gogo_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "b69088d94c7c820f3a327a62485d0ee6ae979e8c4dbe5899d6398ae3d817553f"
      url "https://github.com/daFish/gogo-meta/releases/download/v#{version}/gogo_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "e9ac5d7b8bf1a8332b5fd5041bb7fd73d62c49cc5d6d4530c82c610d6b2ea513"
      url "https://github.com/daFish/gogo-meta/releases/download/v#{version}/gogo_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "81f516972250308e41cb37056ddc17aea5a5bdd9d0ee55e647b236831e8cc4e0"
      url "https://github.com/daFish/gogo-meta/releases/download/v#{version}/gogo_#{version}_linux_amd64.tar.gz"
    end
  end

  name "gogo"
  desc "Run commands across multiple Git repositories at once"
  homepage "https://github.com/daFish/gogo-meta"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gogo"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gogo"] if OS.mac?
  end

  # No zap stanza required
end
